In [1]:
# 1. Force remove the wrong 'edgar' package and alternatives
%pip uninstall edgar python-edgar sec-api -y

# 2. Install the correct package (it must be 'edgartools')
%pip install edgartools

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping edgar as it is not installed.
WARNING: Skipping python-edgar as it is not installed.
WARNING: Skipping sec-api as it is not installed.

Requirement already satisfied: edgartools in c:\users\jabob\.conda\conda\lib\site-packages (5.31.3)
Requirement already satisfied: beautifulsoup4>=4.10.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.14.3)
Requirement already satisfied: httpx>=0.25.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.28.1)
Requirement already satisfied: httpxthrottlecache>=0.3.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.3.5)
Requirement already satisfied: humanize>=4.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.15.0)
Requirement already satisfied: jinja2>=3.1.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.1.2)
Requirement already satisfied: lxml>=4.4 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (6.1.0)
Requirement already satisfied: nest-asyncio>=1.5.1 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (1.5.6)
Requirement already satisfied: orjson>=3.6.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.11.9)
Requirement already satisfied: pandas>=2.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.0.3)
Requirement already satisfied: pyarrow>=17.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (24.0.0)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (2.13.3)
Requirement already satisfied: pyrate-limiter>=3.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.1.0)
Requirement already satisfied: rank-bm25>=0.2.1 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.2.2)
Requirement already satisfied: rapidfuzz>=3.5.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (3.14.5)
Requirement already satisfied: rich>=13.8.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (15.0.0)
Requirement already satisfied: stamina>=24.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (26.1.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.10.0)
Requirement already satisfied: textdistance>=4.5.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.6.3)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (4.65.0)
Requirement already satisfied: truststore>=0.9.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (0.10.4)
Requirement already satisfied: unidecode>=1.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from edgartools) (1.2.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\jabob\.conda\conda\lib\site-packages (from beautifulsoup4>=4.10.0->edgartools) (2.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\jabob\.conda\conda\lib\site-packages (from beautifulsoup4>=4.10.0->edgartools) (4.15.0)
Requirement already satisfied: anyio in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (4.13.0)
Requirement already satisfied: certifi in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (1.0.9)
Requirement already satisfied: idna in c:\users\jabob\.conda\conda\lib\site-packages (from httpx>=0.25.0->edgartools) (3.4)
Requirement already satisfied: h11>=0.16 in c:\users\jabob\.conda\conda\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->edgartools) (0.16.0)
Requirement already satisfied: aiofiles>=24.1.0 in c:\users\jabob\.conda\conda\lib\site-packages (from httpxthrottlecache>=0.3.0->edgartools) (25.1.0)
Requirement already satisfied: filelock>=3.18.0 in c:\users\jabob\.conda\conda\lib\site-packages (from httpxthrottlecache>=0.3.0->edgartools) (3.29.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from jinja2>=3.1.0->edgartools) (2.1.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (2.8.2)
Requirement already satisfied: tzdata in c:\users\jabob\.conda\conda\lib\site-packages (from pandas>=2.0.0->edgartools) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\jabob\.conda\conda\lib\site-packages (from pydantic>=2.0.0->edgartools) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\jabob\.conda\conda\lib\site-packages (from rich>=13.8.0->edgartools) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\jabob\.conda\conda\lib\site-packages (from rich>=13.8.0->edgartools) (2.15.1)
Requirement already satisfied: tenacity in c:\users\jabob\.conda\conda\lib\site-packages (from stamina>=24.2.0->edgartools) (8.2.2)
Requirement already satisfied: colorama in c:\users\jabob\.conda\conda\lib\site-packages (from tqdm>=4.62.0->edgartools) (0.4.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\jabob\.conda\conda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->edgartools) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\jabob\.conda\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->edgartools) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# %pip uninstall edgar -y
# ! pip install edgar

# ! pip install sec-api

from edgar import *
set_identity("Jason Rodriguez jabob2002@gmail.com")
import pandas as pd
import numpy as np

c:\Users\jabob\.conda\conda\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\jabob\.conda\conda\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
#  test 


amex = Company("AXP")


cik = amex.cik

files = amex.get_filings(form="10-Q").head(10)

print(cik)

4962

In [4]:
apple = Company("AAPL")


apple_cik = amex.cik

files = apple.get_filings(form="10-Q").head(10)

print(cik)

4962

In [22]:
import pandas as pd

df = files.to_pandas()

df.columns = df.columns.str.lower()

time_stamps_columns = ['filing_date', 'reportdate']


quarter_col = 'reportdate'

df[quarter_col] = pd.to_datetime(df[quarter_col])
df['quarter_year'] = (
    df['reportdate'].dt.year.astype(str) 
    + "'Q" 
    + df['reportdate'].dt.quarter.astype(str)
)

df

,accession_number,filing_date,reportdate,acceptancedatetime,act,form,filenumber,items,size,isxbrl,isinlinexbrl,primarydocument,primarydocdescription,quarter_year
0,0000320193-26-000013,2026-05-01,2026-03-28,2026-05-01 10:01:00+00:00,34,10-Q,001-36743,,5809851,1,1,aapl-20260328.htm,10-Q,2026'Q1
1,0000320193-26-000006,2026-01-30,2025-12-27,2026-01-30 11:01:32+00:00,34,10-Q,001-36743,,5191740,1,1,aapl-20251227.htm,10-Q,2025'Q4
2,0000320193-25-000073,2025-08-01,2025-06-28,2025-08-01 10:00:42+00:00,34,10-Q,001-36743,,5304776,1,1,aapl-20250628.htm,10-Q,2025'Q2
3,0000320193-25-000057,2025-05-02,2025-03-29,2025-05-02 10:00:46+00:00,34,10-Q,001-36743,,5299807,1,1,aapl-20250329.htm,10-Q,2025'Q1
4,0000320193-25-000008,2025-01-31,2024-12-28,2025-01-31 11:01:27+00:00,34,10-Q,001-36743,,5150277,1,1,aapl-20241228.htm,10-Q,2024'Q4
5,0000320193-24-000081,2024-08-02,2024-06-29,2024-08-01 22:03:34+00:00,34,10-Q,001-36743,,5372771,1,1,aapl-20240629.htm,10-Q,2024'Q2
6,0000320193-24-000069,2024-05-03,2024-03-30,2024-05-02 22:04:25+00:00,34,10-Q,001-36743,,5284139,1,1,aapl-20240330.htm,10-Q,2024'Q1
7,0000320193-24-000006,2024-02-02,2023-12-30,2024-02-01 23:03:38+00:00,34,10-Q,001-36743,,4984121,1,1,aapl-20231230.htm,10-Q,2023'Q4
8,0000320193-23-000077,2023-08-04,2023-07-01,2023-08-03 22:04:43+00:00,34,10-Q,001-36743,,5939898,1,1,aapl-20230701.htm,10-Q,2023'Q3
9,0000320193-23-000064,2023-05-05,2023-04-01,2023-05-04 22:03:52+00:00,34,10-Q,001-36743,,6314786,1,1,aapl-20230401.htm,10-Q,2023'Q2

In [96]:
def fetching_reportings(ticker):
    all_dfs = []

    ticker_var = Company(ticker)
    ticker_cik = ticker_var.cik
    files = ticker_var.get_filings(form=["10-Q", "10-K"])

    for filing in files:
        try:
            xbrl = filing.xbrl()
            if not xbrl:
                continue
                
            income_statement = xbrl.statements.income_statement()
            if income_statement is None:
                continue

            df = income_statement.to_dataframe()
            df = df[df['abstract'] == False].copy()
            
            date_cols = [col for col in df.columns if col[0].isdigit()]
            df = df[['label'] + date_cols]
            df['label'] = df['label'].str.strip().str.replace(':', '')

            df = df.drop_duplicates(subset='label', keep='first')
            df = df.set_index('label')

            df_T = df.T
            df_T.index.name = 'period'
            df_T = df_T.reset_index()
            
            df_T['date'] = pd.to_datetime(df_T['period'].str.extract(r'(\d{4}-\d{2}-\d{2})')[0])
            df_T['period_type'] = df_T['period'].str.extract(r'\((\w+)\)')[0]

            # ---- CHANGE IS HERE ----
            df_T['period_type'] = df_T['period_type'].fillna(
                'Q4' if filing.form == '10-K' else 'SKIP'
            )
            # ------------------------

            df_T = df_T[df_T['period_type'].isin(['Q1', 'Q2', 'Q3', 'Q4'])]
            df_T = df_T.drop(columns=['period', 'period_type']).set_index('date')
            df_T = df_T.apply(pd.to_numeric, errors='coerce')
            
            all_dfs.append(df_T)

        except Exception as e:
            print(f"Failed processing {filing.company} ({filing.filing_date}): {e}")

    df_final = pd.concat(all_dfs)
    df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')]
    df_final = df_final[~df_final.index.duplicated(keep='first')]
    df_final = df_final.sort_index()

    df_final.columns = df_final.columns.str.lower().str.replace(' ', '_')
    return df_final

data = fetching_reportings('AAPL')

print(data)

Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='2010-01-25', accession_no='0001193125-10-012091')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`


Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='2009-04-27', accession_no='0001193125-09-087629')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='2009-04-27', accession_no='0001193125-09-087629')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2009-04-23', accession_no='0001193125-09-085781')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2009-01-23', accession_no='0001193125-09-009937')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2008-11-05', accession_no='0001193125-08-224958')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-07-23', accession_no='0001193125-08-156421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-05-01', accession_no='0001193125-08-097759')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2008-02-01', accession_no='0001193125-08-017426')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2007-11-15', accession_no='0001047469-07-009340')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-08-08', accession_no='0001104659-07-059873')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-05-10', accession_no='0001104659-07-037745')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2007-02-02', accession_no='0001104659-07-006648')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2006-12-29', accession_no='0001104659-06-084288')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-12-29', accession_no='0001104659-06-084286')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-05-05', accession_no='0001104659-06-031303')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2006-02-03', accession_no='0001104659-06-005910')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2005-12-01', accession_no='0001104659-05-058421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-08-03', accession_no='0001104659-05-035792')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-05-04', accession_no='0001104659-05-020421')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2005-02-01', accession_no='0001104659-05-003520')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2004-12-03', accession_no='0001047469-04-035975')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-08-05', accession_no='0001104659-04-022384')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-05-06', accession_no='0001104659-04-013021')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2004-02-10', accession_no='0001104659-04-003080')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2003-12-19', accession_no='0001047469-03-041604')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-08-12', accession_no='0001104659-03-017766')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-05-13', accession_no='0001104659-03-009489')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2003-02-10', accession_no='0001047469-03-004566')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2002-12-19', accession_no='0001047469-02-007674')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-08-09', accession_no='0000912057-02-030796')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-05-14', accession_no='0000912057-02-020280')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2002-02-11', accession_no='0000912057-02-004945')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-08-13', accession_no='0000912057-01-528148')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-05-14', accession_no='0000912057-01-515409')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2001-02-12', accession_no='0000912057-01-004642')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='2000-12-14', accession_no='0000912057-00-053623')
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
Subheader 'COMPANY DATA' not found in header ']		IRS NUMBER'
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-07-31', accession_no='0000912057-00-033901')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-05-11', accession_no='0000912057-00-023442')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='2000-02-01', accession_no='0000912057-00-003201')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1999-12-22', accession_no='0000912057-99-010244')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-08-06', accession_no='0000320193-99-000009')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-05-11', accession_no='0000320193-99-000004')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1999-02-08', accession_no='0000320193-99-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-08-10', accession_no='0000320193-98-000008')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-05-11', accession_no='0000320193-98-000006')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1998-02-09', accession_no='0000320193-98-000003')

Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='1998-01-23', accession_no='0001047469-98-001822')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K/A', filing_date='1998-01-23', accession_no='0001047469-98-001822')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1997-12-05', accession_no='0001047469-97-006960')

Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='1997-10-07', accession_no='0000320193-97-000021')
is an amended filing and may not contain full XBRL data e.g. some statements might be missing.
Consider using the original filing instead if available with `get_filings(form="10-K", amendments=False)`

No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q/A', filing_date='1997-10-07', accession_no='0000320193-97-000021')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-08-11', accession_no='0000320193-97-000014')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-05-12', accession_no='0000320193-97-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1997-02-10', accession_no='0000320193-97-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1996-12-19', accession_no='0000320193-96-000023')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-08-12', accession_no='0000320193-96-000018')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-05-13', accession_no='0000320193-96-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1996-02-12', accession_no='0000320193-96-000002')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1995-12-19', accession_no='0000320193-95-000016')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-08-11', accession_no='0000320193-95-000011')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-05-15', accession_no='0000320193-95-000008')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1995-02-09', accession_no='0000320193-95-000003')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-K', filing_date='1994-12-13', accession_no='0000320193-94-000016')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1994-08-12', accession_no='0000320193-94-000013')
No XBRL attachments found in filing Filing(company='Apple Inc.', cik=320193, form='10-Q', filing_date='1994-01-26', accession_no='0000320193-94-000002')

label          net_sales      products        iphone           mac  \
date
2008-06-28           NaN           NaN           NaN           NaN
2008-12-27           NaN           NaN           NaN           NaN
2009-03-28           NaN           NaN           NaN           NaN
2009-06-27  9.734000e+09           NaN           NaN           NaN
2009-12-26  1.568300e+10           NaN           NaN           NaN
2010-03-27  1.349900e+10           NaN           NaN           NaN
2010-06-26  1.570000e+10           NaN           NaN           NaN
2010-12-25  2.674100e+10           NaN           NaN           NaN
2011-03-26  2.466700e+10           NaN           NaN           NaN
2011-06-25  2.857100e+10           NaN           NaN           NaN
2011-12-31  4.633300e+10           NaN           NaN           NaN
2012-03-31  3.918600e+10           NaN           NaN           NaN
2012-06-30  3.502300e+10           NaN           NaN           NaN
2012-12-29  5.451200e+10           NaN           NaN           NaN
2013-03-30  4.360300e+10           NaN           NaN           NaN
2013-06-29  3.532300e+10           NaN           NaN           NaN
2013-12-28  5.759400e+10           NaN           NaN           NaN
2014-03-29  4.564600e+10           NaN           NaN           NaN
2014-06-28  3.743200e+10           NaN           NaN           NaN
2014-12-27  7.459900e+10           NaN           NaN           NaN
2015-03-28  5.801000e+10           NaN           NaN           NaN
2015-06-27  4.960500e+10           NaN           NaN           NaN
2015-12-26  7.587200e+10           NaN           NaN           NaN
2016-03-26  5.055700e+10           NaN           NaN           NaN
2016-06-25  4.235800e+10           NaN           NaN           NaN
2016-12-31  7.835100e+10           NaN           NaN           NaN
2017-04-01  5.289600e+10           NaN           NaN           NaN
2017-07-01  4.540800e+10           NaN           NaN           NaN
2017-12-30  8.829300e+10  7.916400e+10  6.110400e+10  6.824000e+09
2018-03-31  6.113700e+10  5.128700e+10  3.755900e+10  5.776000e+09
2018-06-30  5.326500e+10  4.309500e+10  2.947000e+10  5.258000e+09
2018-12-29  8.431000e+10  7.343500e+10  5.198200e+10  7.416000e+09
2019-03-30  5.801500e+10  4.656500e+10  3.105100e+10  5.513000e+09
2019-06-29  5.380900e+10  4.235400e+10  2.598600e+10  5.820000e+09
2019-12-28  9.181900e+10  7.910400e+10  5.595700e+10  7.160000e+09
2020-03-28  5.831300e+10  4.496500e+10  2.896200e+10  5.351000e+09
2020-06-27  5.968500e+10  4.652900e+10  2.641800e+10  7.079000e+09
2020-12-26  1.114390e+11  9.567800e+10  6.559700e+10  8.675000e+09
2021-03-27  8.958400e+10  7.268300e+10  4.793800e+10  9.102000e+09
2021-06-26  8.143400e+10  6.394800e+10  3.957000e+10  8.235000e+09
2021-12-25  1.239450e+11  1.044290e+11  7.162800e+10  1.085200e+10
2022-03-26  9.727800e+10  7.745700e+10  5.057000e+10  1.043500e+10
2022-06-25  8.295900e+10  6.335500e+10  4.066500e+10  7.382000e+09
2022-12-31  1.171540e+11  9.638800e+10  6.577500e+10  7.735000e+09
2023-04-01  9.483600e+10  7.392900e+10  5.133400e+10  7.168000e+09
2023-07-01  8.179700e+10  6.058400e+10  3.966900e+10  6.840000e+09
2023-12-30  1.195750e+11  9.645800e+10  6.970200e+10  7.780000e+09
2024-03-30  9.075300e+10  6.688600e+10  4.596300e+10  7.451000e+09
2024-06-29  8.577700e+10  6.156400e+10  3.929600e+10  7.009000e+09
2024-12-28  1.243000e+11  9.796000e+10  6.913800e+10  8.987000e+09
2025-03-29  9.535900e+10  6.871400e+10  4.684100e+10  7.949000e+09
2025-06-28  9.403600e+10  6.661300e+10  4.458200e+10  8.046000e+09
2025-12-27  1.437560e+11  1.137430e+11  8.526900e+10  8.386000e+09
2026-03-28  1.111840e+11  8.020800e+10  5.699400e+10  8.399000e+09

label               ipad  wearables,_home_and_accessories      services  \
date
2008-06-28           NaN                              NaN           NaN
2008-12-27           NaN                              NaN           NaN
2009-03-28           NaN                              NaN           NaN
2009-06-27           NaN                              NaN           NaN
2009-12-26           NaN                              NaN           NaN
2010-03-27           NaN                              NaN           NaN
2010-06-26           NaN                              NaN           NaN
2010-12-25           NaN                              NaN           NaN
2011-03-26           NaN                              NaN           NaN
2011-06-25           NaN                              NaN           NaN
2011-12-31           NaN                              NaN           NaN
2012-03-31           NaN                              NaN           NaN
2012-06-30           NaN                              NaN           NaN
2012-12-29           NaN                              NaN           NaN
2013-03-30           NaN                              NaN           NaN
2013-06-29           NaN                              NaN           NaN
2013-12-28           NaN                              NaN           NaN
2014-03-29           NaN                              NaN           NaN
2014-06-28           NaN                              NaN           NaN
2014-12-27           NaN                              NaN           NaN
2015-03-28           NaN                              NaN           NaN
2015-06-27           NaN                              NaN           NaN
2015-12-26           NaN                              NaN           NaN
2016-03-26           NaN                              NaN           NaN
2016-06-25           NaN                              NaN           NaN
2016-12-31           NaN                              NaN           NaN
2017-04-01           NaN                              NaN           NaN
2017-07-01           NaN                              NaN           NaN
2017-12-30  5.755000e+09                     5.481000e+09  9.129000e+09
2018-03-31  4.008000e+09                     3.944000e+09  9.850000e+09
2018-06-30  4.634000e+09                     3.733000e+09  1.017000e+10
2018-12-29  6.729000e+09                     7.308000e+09  1.087500e+10
2019-03-30  4.872000e+09                     5.129000e+09  1.145000e+10
2019-06-29  5.023000e+09                     5.525000e+09  1.145500e+10
2019-12-28  5.977000e+09                     1.001000e+10  1.271500e+10
2020-03-28  4.368000e+09                     6.284000e+09  1.334800e+10
2020-06-27  6.582000e+09                     6.450000e+09  1.315600e+10
2020-12-26  8.435000e+09                     1.297100e+10  1.576100e+10
2021-03-27  7.807000e+09                     7.836000e+09  1.690100e+10
2021-06-26  7.368000e+09                     8.775000e+09  1.748600e+10
2021-12-25  7.248000e+09                     1.470100e+10  1.951600e+10
2022-03-26  7.646000e+09                     8.806000e+09  1.982100e+10
2022-06-25  7.224000e+09                     8.084000e+09  1.960400e+10
2022-12-31  9.396000e+09                     1.348200e+10  2.076600e+10
2023-04-01  6.670000e+09                     8.757000e+09  2.090700e+10
2023-07-01  5.791000e+09                     8.284000e+09  2.121300e+10
2023-12-30  7.023000e+09                     1.195300e+10  2.311700e+10
2024-03-30  5.559000e+09                     7.913000e+09  2.386700e+10
2024-06-29  7.162000e+09                     8.097000e+09  2.421300e+10
2024-12-28  8.088000e+09                     1.174700e+10  2.634000e+10
2025-03-29  6.402000e+09                     7.522000e+09  2.664500e+10
2025-06-28  6.581000e+09                     7.404000e+09  2.742300e+10
2025-12-27  8.595000e+09                     1.149300e+10  3.001300e+10
2026-03-28  6.914000e+09                     7.901000e+09  3.097600e+10

label       operating_segments_-_americas  operating_segments_-_europe  \
date
2008-06-28                            NaN                          NaN
2008-12-27                            NaN                          NaN
2009-03-28                            NaN                          NaN
2009-06-27                            NaN                          NaN
2009-12-26                            NaN                          NaN
2010-03-27                            NaN                          NaN
2010-06-26                            NaN                          NaN
2010-12-25                            NaN                          NaN
2011-03-26                            NaN                          NaN
2011-06-25                            NaN                          NaN
2011-12-31                            NaN                          NaN
2012-03-31                            NaN                          NaN
2012-06-30                            NaN                          NaN
2012-12-29                            NaN                          NaN
2013-03-30                            NaN                          NaN
2013-06-29                            NaN                          NaN
2013-12-28                            NaN                          NaN
2014-03-29                            NaN                          NaN
2014-06-28                            NaN                          NaN
2014-12-27                            NaN                          NaN
2015-03-28                            NaN                          NaN
2015-06-27                            NaN                          NaN
2015-12-26                            NaN                          NaN
2016-03-26                            NaN                          NaN
2016-06-25                            NaN                          NaN
2016-12-31                            NaN                          NaN
2017-04-01                            NaN                          NaN
2017-07-01                            NaN                          NaN
2017-12-30                            NaN                          NaN
2018-03-31                            NaN                          NaN
2018-06-30                            NaN                          NaN
2018-12-29                            NaN                          NaN
2019-03-30                            NaN                          NaN
2019-06-29                            NaN                          NaN
2019-12-28                            NaN                          NaN
2020-03-28                            NaN                          NaN
2020-06-27                            NaN                          NaN
2020-12-26                            NaN                          NaN
2021-03-27                            NaN                          NaN
2021-06-26                            NaN                          NaN
2021-12-25                            NaN                          NaN
2022-03-26                            NaN                          NaN
2022-06-25                            NaN                          NaN
2022-12-31                            NaN                          NaN
2023-04-01                            NaN                          NaN
2023-07-01                            NaN                          NaN
2023-12-30                            NaN                          NaN
2024-03-30                            NaN                          NaN
2024-06-29                            NaN                          NaN
2024-12-28                   5.264800e+10                 3.386100e+10
2025-03-29                   4.031500e+10                 2.445400e+10
2025-06-28                            NaN                          NaN
2025-12-27                   5.852900e+10                 3.814600e+10
2026-03-28                   4.509300e+10                 2.805500e+10

label       operating_segments_-_greater_china  ...  portables  \
date                                            ...
2008-06-28                                 NaN  ...        NaN
2008-12-27                                 NaN  ...        NaN
2009-03-28                                 NaN  ...        NaN
2009-06-27                                 NaN  ...        NaN
2009-12-26                                 NaN  ...        NaN
2010-03-27                                 NaN  ...        NaN
2010-06-26                                 NaN  ...        NaN
2010-12-25                                 NaN  ...        NaN
2011-03-26                                 NaN  ...        NaN
2011-06-25                                 NaN  ...        NaN
2011-12-31                                 NaN  ...        NaN
2012-03-31                                 NaN  ...        NaN
2012-06-30                                 NaN  ...        NaN
2012-12-29                                 NaN  ...        NaN
2013-03-30                                 NaN  ...        NaN
2013-06-29                                 NaN  ...        NaN
2013-12-28                                 NaN  ...        NaN
2014-03-29                                 NaN  ...        NaN
2014-06-28                                 NaN  ...        NaN
2014-12-27                                 NaN  ...        NaN
2015-03-28                                 NaN  ...        NaN
2015-06-27                                 NaN  ...        NaN
2015-12-26                                 NaN  ...        NaN
2016-03-26                                 NaN  ...        NaN
2016-06-25                                 NaN  ...        NaN
2016-12-31                                 NaN  ...        NaN
2017-04-01                                 NaN  ...        NaN
2017-07-01                                 NaN  ...        NaN
2017-12-30                                 NaN  ...        NaN
2018-03-31                                 NaN  ...        NaN
2018-06-30                                 NaN  ...        NaN
2018-12-29                                 NaN  ...        NaN
2019-03-30                                 NaN  ...        NaN
2019-06-29                                 NaN  ...        NaN
2019-12-28                                 NaN  ...        NaN
2020-03-28                                 NaN  ...        NaN
2020-06-27                                 NaN  ...        NaN
2020-12-26                                 NaN  ...        NaN
2021-03-27                                 NaN  ...        NaN
2021-06-26                                 NaN  ...        NaN
2021-12-25                                 NaN  ...        NaN
2022-03-26                                 NaN  ...        NaN
2022-06-25                                 NaN  ...        NaN
2022-12-31                                 NaN  ...        NaN
2023-04-01                                 NaN  ...        NaN
2023-07-01                                 NaN  ...        NaN
2023-12-30                                 NaN  ...        NaN
2024-03-30                                 NaN  ...        NaN
2024-06-29                                 NaN  ...        NaN
2024-12-28                        1.851300e+10  ...        NaN
2025-03-29                        1.600200e+10  ...        NaN
2025-06-28                                 NaN  ...        NaN
2025-12-27                        2.552600e+10  ...        NaN
2026-03-28                        2.049700e+10  ...        NaN

label       non-operating_income_(expense)  \
date
2008-06-28                     118000000.0
2008-12-27                     158000000.0
2009-03-28                      63000000.0
2009-06-27                             NaN
2009-12-26                      33000000.0
2010-03-27                      50000000.0
2010-06-26                      58000000.0
2010-12-25                             NaN
2011-03-26                             NaN
2011-06-25                             NaN
2011-12-31                             NaN
2012-03-31                             NaN
2012-06-30                             NaN
2012-12-29                             NaN
2013-03-30                             NaN
2013-06-29                             NaN
2013-12-28                             NaN
2014-03-29                             NaN
2014-06-28                             NaN
2014-12-27                             NaN
2015-03-28                             NaN
2015-06-27                             NaN
2015-12-26                             NaN
2016-03-26                             NaN
2016-06-25                             NaN
2016-12-31                             NaN
2017-04-01                             NaN
2017-07-01                             NaN
2017-12-30                             NaN
2018-03-31                             NaN
2018-06-30                             NaN
2018-12-29                             NaN
2019-03-30                             NaN
2019-06-29                             NaN
2019-12-28                             NaN
2020-03-28                             NaN
2020-06-27                             NaN
2020-12-26                             NaN
2021-03-27                             NaN
2021-06-26                             NaN
2021-12-25                             NaN
2022-03-26                             NaN
2022-06-25                             NaN
2022-12-31                             NaN
2023-04-01                             NaN
2023-07-01                             NaN
2023-12-30                             NaN
2024-03-30                             NaN
2024-06-29                             NaN
2024-12-28                             NaN
2025-03-29                             NaN
2025-06-28                             NaN
2025-12-27                             NaN
2026-03-28                             NaN

label       weighted_average_shares_outstanding,_diluted  income_tax_expense  \
date
2008-06-28                                   903167000.0        4.380000e+08
2008-12-27                                           NaN        1.004000e+09
2009-03-28                                           NaN        7.660000e+08
2009-06-27                                   909160000.0        8.640000e+08
2009-12-26                                   919783000.0        1.380000e+09
2010-03-27                                   922878000.0        9.550000e+08
2010-06-26                                   927361000.0        1.039000e+09
2010-12-25                                           NaN                 NaN
2011-03-26                                           NaN                 NaN
2011-06-25                                           NaN                 NaN
2011-12-31                                           NaN                 NaN
2012-03-31                                           NaN                 NaN
2012-06-30                                           NaN                 NaN
2012-12-29                                           NaN                 NaN
2013-03-30                                           NaN                 NaN
2013-06-29                                           NaN                 NaN
2013-12-28                                           NaN                 NaN
2014-03-29                                           NaN                 NaN
2014-06-28                                           NaN                 NaN
2014-12-27                                           NaN                 NaN
2015-03-28                                           NaN                 NaN
2015-06-27                                           NaN                 NaN
2015-12-26                                           NaN                 NaN
2016-03-26                                           NaN                 NaN
2016-06-25                                           NaN                 NaN
2016-12-31                                           NaN                 NaN
2017-04-01                                           NaN                 NaN
2017-07-01                                           NaN                 NaN
2017-12-30                                           NaN                 NaN
2018-03-31                                           NaN                 NaN
2018-06-30                                           NaN                 NaN

In [101]:
def calculating_margins(data): 
    df_margins = None 
    
    try:
        margins = ['net_sales', 'gross_margin', 'net_income']
        
        if set(margins).issubset(data.columns):
            
            df_margins = data[margins].copy()

            df_margins['gross_margin_rate'] = (df_margins['gross_margin'] / df_margins['net_sales']) * 100
            df_margins['net_margin_rate'] = (df_margins['net_income'] / df_margins['net_sales']) * 100

            df_margins.dropna(axis=0, inplace=True)
            
            df_margins['bps_difference'] = (df_margins['gross_margin_rate'] - df_margins['net_margin_rate']) 
            df_margins['dollar_difference'] = df_margins['gross_margin'] - df_margins['net_income'] 
        else:
            print("yikes. One or more required columns are missing from the DataFrame.") 
            
    # Catching generic Exceptions ensures you see math/key errors, not just NameErrors
    except Exception as e:
        print(f"Error during calculation: {e}")

    return df_margins

apple_margins = calculating_margins(data)

apple_margins

label,net_sales,gross_margin,net_income,gross_margin_rate,net_margin_rate,bps_difference,dollar_difference
date,,,,,,,
2009-06-27,9.734000e+09,3.983000e+09,1.828000e+09,40.918430,18.779536,22.138895,2.155000e+09
2009-12-26,1.568300e+10,6.411000e+09,3.378000e+09,40.878658,21.539246,19.339412,3.033000e+09
2010-03-27,1.349900e+10,5.625000e+09,3.074000e+09,41.669753,22.772057,18.897696,2.551000e+09
2010-06-26,1.570000e+10,6.136000e+09,3.253000e+09,39.082803,20.719745,18.363057,2.883000e+09
2010-12-25,2.674100e+10,1.029800e+10,6.004000e+09,38.510153,22.452414,16.057739,4.294000e+09
2011-03-26,2.466700e+10,1.021800e+10,5.987000e+09,41.423765,24.271294,17.152471,4.231000e+09
2011-06-25,2.857100e+10,1.192200e+10,7.308000e+09,41.727626,25.578384,16.149242,4.614000e+09
2011-12-31,4.633300e+10,2.070300e+10,1.306400e+10,44.683055,28.195886,16.487169,7.639000e+09
2012-03-31,3.918600e+10,1.856400e+10,1.162200e+10,47.374062,29.658552,17.715511,6.942000e+09
2012-06-30,3.502300e+10,1.499400e+10,8.824000e+09,42.811866,25.194872,17.616995,6.170000e+09
2012-12-29,5.451200e+10,2.106000e+10,1.307800e+10,38.633695,23.991048,14.642647,7.982000e+09
2013-03-30,4.360300e+10,1.634900e+10,9.547000e+09,37.495126,21.895282,15.599844,6.802000e+09
2013-06-29,3.532300e+10,1.302400e+10,6.900000e+09,36.871160,19.534015,17.337146,6.124000e+09
2013-12-28,5.759400e+10,2.184600e+10,1.307200e+10,37.931034,22.696809,15.234226,8.774000e+09
2014-03-29,4.564600e+10,1.794700e+10,1.022300e+10,39.317793,22.396267,16.921527,7.724000e+09
2014-06-28,3.743200e+10,1.473500e+10,7.748000e+09,39.364715,20.698867,18.665847,6.987000e+09
2014-12-27,7.459900e+10,2.974100e+10,1.802400e+10,39.867827,24.161182,15.706645,1.171700e+10
2015-03-28,5.801000e+10,2.365600e+10,1.356900e+10,40.779176,23.390795,17.388381,1.008700e+10
2015-06-27,4.960500e+10,1.968100e+10,1.067700e+10,39.675436,21.524040,18.151396,9.004000e+09
2015-12-26,7.587200e+10,3.042300e+10,1.836100e+10,40.097796,24.199968,15.897828,1.206200e+10
2016-03-26,5.055700e+10,1.992100e+10,1.051600e+10,39.403050,20.800285,18.602765,9.405000e+09
2016-06-25,4.235800e+10,1.610600e+10,7.796000e+09,38.023514,18.405024,19.618490,8.310000e+09
2016-12-31,7.835100e+10,3.017600e+10,1.789100e+10,38.513867,22.834425,15.679443,1.228500e+10
2017-04-01,5.289600e+10,2.059100e+10,1.102900e+10,38.927329,20.850348,18.076981,9.562000e+09
2017-07-01,4.540800e+10,1.748800e+10,8.717000e+09,38.513037,19.197058,19.315980,8.771000e+09
2017-12-30,8.829300e+10,3.391200e+10,2.006500e+10,38.408481,22.725471,15.683010,1.384700e+10
2018-03-31,6.113700e+10,2.342200e+10,1.382200e+10,38.310679,22.608241,15.702439,9.600000e+09
2018-06-30,5.326500e+10,2.042100e+10,1.151900e+10,38.338496,21.625833,16.712663,8.902000e+09
2018-12-29,8.431000e+10,3.203100e+10,1.996500e+10,37.991935,23.680465,14.311470,1.206600e+10
2019-03-30,5.801500e+10,2.182100e+10,1.156100e+10,37.612686,19.927605,17.685081,1.026000e+10
2019-06-29,5.380900e+10,2.022700e+10,1.004400e+10,37.590366,18.666022,18.924344,1.018300e+10
2019-12-28,9.181900e+10,3.521700e+10,2.223600e+10,38.354807,24.217210,14.137597,1.298100e+10
2020-03-28,5.831300e+10,2.237000e+10,1.124900e+10,38.361943,19.290724,19.071219,1.112100e+10
2020-06-27,5.968500e+10,2.268000e+10,1.125300e+10,37.999497,18.853983,19.145514,1.142700e+10
2020-12-26,1.114390e+11,4.432800e+10,2.875500e+10,39.777816,25.803354,13.974461,1.557300e+10
2021-03-27,8.958400e+10,3.807900e+10,2.363000e+10,42.506474,26.377478,16.128996,1.444900e+10
2021-06-26,8.143400e+10,3.525500e+10,2.174400e+10,43.292728,26.701378,16.591350,1.351100e+10
2021-12-25,1.239450e+11,5.424300e+10,3.463000e+10,43.763766,27.939812,15.823954,1.961300e+10
2022-03-26,9.727800e+10,4.255900e+10,2.501000e+10,43.749872,25.709821,18.040050,1.754900e+10
2022-06-25,8.295900e+10,3.588500e+10,1.944200e+10,43.256307,23.435673,19.820634,1.644300e+10
2022-12-31,1.171540e+11,5.033200e+10,2.999800e+10,42.962255,25.605613,17.356642,2.033400e+10
2023-04-01,9.483600e+10,4.197600e+10,2.416000e+10,44.261673,25.475558,18.786115,1.781600e+10
2023-07-01,8.179700e+10,3.641300e+10,1.988100e+10,44.516303,24.305292,20.211010,1.653200e+10
2023-12-30,1.195750e+11,5.485500e+10,3.391600e+10,45.874974,28.363788,17.511185,2.093900e+10
2024-03-30,9.075300e+10,4.227100e+10,2.363600e+10,46.578075,26.044318,20.533756,1.863500e+10
2024-06-29,8.577700e+10,3.967800e+10,2.144800e+10,46.257155,25.004372,21.252783,1.823000e+10
2024-12-28,1.243000e+11,5.827500e+10,3.633000e+10,46.882542,29.227675,17.654867,2.194500e+10
2025-03-29,9.535900e+10,4.486700e+10,2.478000e+10,47.050619,25.986011,21.064608,2.008700e+10
2025-06-28,9.403600e+10,4.371800e+10,2.343400e+10,46.490706,24.920243,21.570462,2.028400e+10
2025-12-27,1.437560e+11,6.923100e+10,4.209700e+10,48.158686,29.283647,18.875038,2.713400e+10
2026-03-28,1.111840e+11,5.478100e+10,2.957800e+10,49.270579,26.602749,22.667830,2.520300e+10

In [ ]:
# import matplotlib.pyplot as plt

# plt.figure(figsize=(20, 8))

# df_margins.plot(y='gross_margin', ax=plt.gca(), linewidth=2)
# plt.title('Gross Margin Evolution Across Financial Quarters', fontsize=16, fontweight='bold', pad=15)
# plt.xlabel('Report Date / Quarter', fontsize=12)
# plt.ylabel('Gross Margin Value', fontsize=12)
# plt.grid(True, linestyle='--', alpha=0.6) # Adds a light background grid
# plt.tight_layout()
# plt.show()

# df_margins.plot(y ='net_margin')

label,net_sales,gross_margin,net_income,gross_margin_rate,net_margin_rate,bps_difference,dollar_difference
date,,,,,,,
2009-06-27,9.734000e+09,3.983000e+09,1.828000e+09,40.918430,18.779536,22.138895,2.155000e+09
2009-12-26,1.568300e+10,6.411000e+09,3.378000e+09,40.878658,21.539246,19.339412,3.033000e+09
2010-03-27,1.349900e+10,5.625000e+09,3.074000e+09,41.669753,22.772057,18.897696,2.551000e+09
2010-06-26,1.570000e+10,6.136000e+09,3.253000e+09,39.082803,20.719745,18.363057,2.883000e+09
2010-12-25,2.674100e+10,1.029800e+10,6.004000e+09,38.510153,22.452414,16.057739,4.294000e+09
2011-03-26,2.466700e+10,1.021800e+10,5.987000e+09,41.423765,24.271294,17.152471,4.231000e+09
2011-06-25,2.857100e+10,1.192200e+10,7.308000e+09,41.727626,25.578384,16.149242,4.614000e+09
2011-12-31,4.633300e+10,2.070300e+10,1.306400e+10,44.683055,28.195886,16.487169,7.639000e+09
2012-03-31,3.918600e+10,1.856400e+10,1.162200e+10,47.374062,29.658552,17.715511,6.942000e+09
2012-06-30,3.502300e+10,1.499400e+10,8.824000e+09,42.811866,25.194872,17.616995,6.170000e+09
2012-12-29,5.451200e+10,2.106000e+10,1.307800e+10,38.633695,23.991048,14.642647,7.982000e+09
2013-03-30,4.360300e+10,1.634900e+10,9.547000e+09,37.495126,21.895282,15.599844,6.802000e+09
2013-06-29,3.532300e+10,1.302400e+10,6.900000e+09,36.871160,19.534015,17.337146,6.124000e+09
2013-12-28,5.759400e+10,2.184600e+10,1.307200e+10,37.931034,22.696809,15.234226,8.774000e+09
2014-03-29,4.564600e+10,1.794700e+10,1.022300e+10,39.317793,22.396267,16.921527,7.724000e+09
2014-06-28,3.743200e+10,1.473500e+10,7.748000e+09,39.364715,20.698867,18.665847,6.987000e+09
2014-12-27,7.459900e+10,2.974100e+10,1.802400e+10,39.867827,24.161182,15.706645,1.171700e+10
2015-03-28,5.801000e+10,2.365600e+10,1.356900e+10,40.779176,23.390795,17.388381,1.008700e+10
2015-06-27,4.960500e+10,1.968100e+10,1.067700e+10,39.675436,21.524040,18.151396,9.004000e+09
2015-12-26,7.587200e+10,3.042300e+10,1.836100e+10,40.097796,24.199968,15.897828,1.206200e+10
2016-03-26,5.055700e+10,1.992100e+10,1.051600e+10,39.403050,20.800285,18.602765,9.405000e+09
2016-06-25,4.235800e+10,1.610600e+10,7.796000e+09,38.023514,18.405024,19.618490,8.310000e+09
2016-12-31,7.835100e+10,3.017600e+10,1.789100e+10,38.513867,22.834425,15.679443,1.228500e+10
2017-04-01,5.289600e+10,2.059100e+10,1.102900e+10,38.927329,20.850348,18.076981,9.562000e+09
2017-07-01,4.540800e+10,1.748800e+10,8.717000e+09,38.513037,19.197058,19.315980,8.771000e+09
2017-12-30,8.829300e+10,3.391200e+10,2.006500e+10,38.408481,22.725471,15.683010,1.384700e+10
2018-03-31,6.113700e+10,2.342200e+10,1.382200e+10,38.310679,22.608241,15.702439,9.600000e+09
2018-06-30,5.326500e+10,2.042100e+10,1.151900e+10,38.338496,21.625833,16.712663,8.902000e+09
2018-12-29,8.431000e+10,3.203100e+10,1.996500e+10,37.991935,23.680465,14.311470,1.206600e+10
2019-03-30,5.801500e+10,2.182100e+10,1.156100e+10,37.612686,19.927605,17.685081,1.026000e+10
2019-06-29,5.380900e+10,2.022700e+10,1.004400e+10,37.590366,18.666022,18.924344,1.018300e+10
2019-12-28,9.181900e+10,3.521700e+10,2.223600e+10,38.354807,24.217210,14.137597,1.298100e+10
2020-03-28,5.831300e+10,2.237000e+10,1.124900e+10,38.361943,19.290724,19.071219,1.112100e+10
2020-06-27,5.968500e+10,2.268000e+10,1.125300e+10,37.999497,18.853983,19.145514,1.142700e+10
2020-12-26,1.114390e+11,4.432800e+10,2.875500e+10,39.777816,25.803354,13.974461,1.557300e+10
2021-03-27,8.958400e+10,3.807900e+10,2.363000e+10,42.506474,26.377478,16.128996,1.444900e+10
2021-06-26,8.143400e+10,3.525500e+10,2.174400e+10,43.292728,26.701378,16.591350,1.351100e+10
2021-12-25,1.239450e+11,5.424300e+10,3.463000e+10,43.763766,27.939812,15.823954,1.961300e+10
2022-03-26,9.727800e+10,4.255900e+10,2.501000e+10,43.749872,25.709821,18.040050,1.754900e+10
2022-06-25,8.295900e+10,3.588500e+10,1.944200e+10,43.256307,23.435673,19.820634,1.644300e+10
2022-12-31,1.171540e+11,5.033200e+10,2.999800e+10,42.962255,25.605613,17.356642,2.033400e+10
2023-04-01,9.483600e+10,4.197600e+10,2.416000e+10,44.261673,25.475558,18.786115,1.781600e+10
2023-07-01,8.179700e+10,3.641300e+10,1.988100e+10,44.516303,24.305292,20.211010,1.653200e+10
2023-12-30,1.195750e+11,5.485500e+10,3.391600e+10,45.874974,28.363788,17.511185,2.093900e+10
2024-03-30,9.075300e+10,4.227100e+10,2.363600e+10,46.578075,26.044318,20.533756,1.863500e+10
2024-06-29,8.577700e+10,3.967800e+10,2.144800e+10,46.257155,25.004372,21.252783,1.823000e+10
2024-12-28,1.243000e+11,5.827500e+10,3.633000e+10,46.882542,29.227675,17.654867,2.194500e+10
2025-03-29,9.535900e+10,4.486700e+10,2.478000e+10,47.050619,25.986011,21.064608,2.008700e+10
2025-06-28,9.403600e+10,4.371800e+10,2.343400e+10,46.490706,24.920243,21.570462,2.028400e+10
2025-12-27,1.437560e+11,6.923100e+10,4.209700e+10,48.158686,29.283647,18.875038,2.713400e+10
2026-03-28,1.111840e+11,5.478100e+10,2.957800e+10,49.270579,26.602749,22.667830,2.520300e+10